field: 2fe47f5e-f465-4d4b-bafc-db94fcd20d62 # Narrowcasting Slides
fieldLayouts:
  8799252d-cba1-4d22-9a19-aaa5857df6b1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0ceb5003-324b-47f9-b336-5716ff21c825 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31aaa4e0-fcf9-46d7-8a88-1f5a64b60ccd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a7316bd8-0e45-41fb-bad7-6e74a6f2a902 # Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 375fcf49-f25e-4b97-97ca-38d23bb1ed5a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2928f6e5-130a-431d-a1f3-df296cd1f46a # Text Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a098051-16ec-4052-a9f8-ce674e172a7b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d9d00064-7f3b-483f-97af-6b9c688ae73c # Autoplay speed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9999415-de5c-447a-92ed-127cac9d8de3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c1d68812-8393-416d-8cd8-6d14a80dcc7d
        userCondition: null
fields:
  0ceb5003-324b-47f9-b336-5716ff21c825: # Text
    columnSuffix: nlujdhmf
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2928f6e5-130a-431d-a1f3-df296cd1f46a: # Text Colour
    columnSuffix: tiyqvwsy
    contentColumnType: string(7)
    fieldGroup: null
    handle: textColour
    instructions: null
    name: 'Text Colour'
    searchable: false
    settings:
      defaultColor: '#000000'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  a7316bd8-0e45-41fb-bad7-6e74a6f2a902: # Background Colour
    columnSuffix: wrwllbxa
    contentColumnType: string(7)
    fieldGroup: null
    handle: backgroundColour
    instructions: null
    name: 'Background Colour'
    searchable: false
    settings:
      defaultColor: '#ffffff'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  d9d00064-7f3b-483f-97af-6b9c688ae73c: # Autoplay speed
    columnSuffix: gkhaqrlk
    contentColumnType: integer(10)
    fieldGroup: null
    handle: autoplaySpeed
    instructions: 'Amount of time the slide should be visible for.'
    name: 'Autoplay speed'
    searchable: false
    settings:
      decimals: 0
      defaultValue: 5
      max: null
      min: 1
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: '(e.g. <code>5</code> for 5 seconds)'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: text
name: 'Text slide'
sortOrder: 1
