fieldLayouts:
  c0a16fbb-65e4-4d29-839b-b1c280941d77:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ec848039-61b3-4cd0-8c02-c391d2689421
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dca6fffc-645c-49f0-9467-0f2d5aee2a69
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 9c11c497-5e71-4c81-afd3-317c35414085 # Narrowcasting
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
