fieldLayouts:
  d159507e-00ee-4186-89ce-aa8d13c0f551:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'Name of the cast.'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f3b2ba6d-b575-4f39-b525-17d300b870b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 13ae5af0-a73b-4f42-b8de-035d0bb19544 # Autoplay
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c1f087f-f219-45b1-a6b7-74c22ad88267
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 13ae5af0-a73b-4f42-b8de-035d0bb19544 # Autoplay
                  uid: d5a8ca6c-e1f6-47e3-bb00-d014a9e9fe9c
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: acb24056-4f38-4bed-a13e-0adddccf33aa # Autoplay speed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6ac5b35-736b-4cad-874a-c7c87846b0be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2fe47f5e-f465-4d4b-bafc-db94fcd20d62 # Narrowcasting Slides
            instructions: 'Cast slides.'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef0f778b-85df-48a3-884b-c7a0a32e3d23
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c25aac81-6e27-41ae-a7ca-c390a8be1619
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5bfdcf29-fa8a-4c67-a0bd-334fd6102686 # Transition
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6c2b016-8c69-4e9a-af14-d3b30ff474e6
            userCondition: null
            warning: null
            width: 100
          -
            dismissible: false
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 5bfdcf29-fa8a-4c67-a0bd-334fd6102686 # Transition
                  operator: ni
                  uid: 7f0cf323-9b32-4407-b0eb-7d1362c3f2dc
                  values:
                    - slide
                    - fade
                    - coverflow
                    - flip
                    - cube
                    - cards
                    - creative
              elementType: craft\elements\Entry
              fieldContext: global
            style: tip
            tip: 'Transition settings will only show upon selecting a transition!'
            type: craft\fieldlayoutelements\Tip
            uid: a7f1c671-929c-4e7e-be68-26c4d9218ecc
            userCondition: null
        name: 'Transition settings'
        uid: 4df68f9f-2466-479d-8429-71ff99a49510
        userCondition: null
handle: slides
hasTitleField: true
name: Slides
section: 9c11c497-5e71-4c81-afd3-317c35414085 # Narrowcasting
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
