columnSuffix: null
contentColumnType: string
fieldGroup: bb457270-2eb0-4428-8f92-0f0025dfec80 # Narrowcasting
handle: narrowcastingSlides
instructions: null
name: 'Narrowcasting Slides'
searchable: false
settings:
  contentTable: '{{%matrixcontent_narrowcastingslides}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
